const officialSources = {
  en: [
    {
      label: "Steam store page",
      href: "https://store.steampowered.com/app/1962700/Subnautica_2/",
      note: "Official store page used for Early Access context and broad feature framing.",
    },
    {
      label: "Unknown Worlds Early Access roadmap",
      href: "https://unknownworlds.com/en/news/subnautica-2-early-access-roadmap",
      note: "Official roadmap noting that tools, vehicles, resources, biomes, and systems may continue changing.",
    },
    {
      label: "S2GuideHub gameplay verification",
      href: "",
      note: "Pending. Exact coordinates, final recipes, route timing, and current-build observations must wait for a dated in-game check.",
    },
  ],
  zh: [
    {
      label: "Steam 商店页",
      href: "https://store.steampowered.com/app/1962700/Subnautica_2/",
      note: "用于确认抢先体验背景和官方功能方向。",
    },
    {
      label: "Unknown Worlds 抢先体验路线图",
      href: "https://unknownworlds.com/en/news/subnautica-2-early-access-roadmap",
      note: "官方路线图说明工具、载具、资源、生物群系和系统后续仍可能变化。",
    },
    {
      label: "S2GuideHub 实机核查",
      href: "",
      note: "待完成。精确坐标、最终配方、路线耗时和当前版本观察都必须等带日期的实测。",
    },
  ],
};

const common = {
  en: {
    adLabel: "Advertisement space reserved",
    backToUnlocks: "Back to Unlocks",
    partsHeaders: ["Requirement", "Current note", "Status"],
  },
  zh: {
    adLabel: "广告位预留",
    backToUnlocks: "返回解锁项",
    partsHeaders: ["需求", "当前说明", "状态"],
  },
};

window.guidePages = {
  "feedback-resonator": {
    content: {
      en: {
        ...common.en,
        heroEyebrow: "Blueprint Atlas item guide",
        title: "Feedback Resonator",
        deck: [
          "A source-aware planning page for the Feedback Resonator. This guide explains why the unlock may matter while keeping exact locations, coordinates, material counts, and route timing marked as Needs gameplay check.",
        ],
        summaryAria: "Feedback Resonator status summary",
        summaryItems: [
          { label: "Recommended stage", value: "Early-mid game" },
          { label: "Value point", value: "Utility, signal logic, route sequencing" },
          { label: "Route difficulty", value: "Medium" },
          { label: "Risk level", value: "Medium" },
          { label: "Current status", value: "Needs gameplay check" },
          { label: "Last checked", value: "2026-05-30" },
        ],
        summaryEyebrow: "Summary",
        summaryTitle: "Treat this as a utility unlock candidate, not a finished route",
        summaryBody: [
          "Feedback Resonator is useful to track because utility unlocks can change how later objectives are found, sequenced, or verified. The exact in-game function still needs a S2GuideHub check before this page can make stronger route claims.",
          "For now, this page is a clean template: what value to test, what requirements to confirm, what route assumptions to avoid, and what evidence must be logged before coordinates go public.",
        ],
        relatedLinks: [
          { href: "tadpole-vehicle.html", label: "Tadpole Vehicle" },
          { href: "improved-fins.html", label: "Improved Fins" },
        ],
        statusTitle: "Verification status",
        statusItems: [
          { term: "Known direction", description: "Utility or progression candidate in the first Blueprint Atlas unlock set." },
          { term: "Needs check", description: "Exact function, prerequisites, crafting inputs, and where the unlock is acquired." },
          { term: "Not published here", description: "Coordinates, route time, material totals, and creature pressure claims." },
        ],
        valueEyebrow: "Player value",
        valueTitle: "Why this page belongs in Featured Unlocks",
        valueIntro: [
          "The Atlas should prioritize unlocks that change many later decisions. If Feedback Resonator affects signal reading, scouting, or objective discovery, it can become more important than its own recipe cost suggests.",
        ],
        valueCards: [
          { title: "Route sequencing", body: "May affect which objectives a player should check before committing to deeper travel." },
          { title: "Signal clarity", body: "Worth testing if it makes uncertain objectives easier to identify or return to." },
          { title: "Low-noise planning", body: "A good guide page should separate the tool purpose from unverified map claims." },
          { title: "Co-op coordination", body: "If it changes shared navigation, teams need a clear rule for who carries or uses it." },
        ],
        partsEyebrow: "Required parts",
        partsTitle: "Requirements are intentionally not finalized",
        partsIntro: [
          "Do not treat the table as a recipe. It is the checklist for the first verification pass.",
        ],
        partsRows: [
          { item: "Unlock source", note: "Exact scan, pickup, or blueprint source is not verified by S2GuideHub.", status: "Needs gameplay check" },
          { item: "Crafting materials", note: "Material names and quantities should stay unpublished until checked in the current build.", status: "Needs gameplay check" },
          { item: "Crafting station or prerequisite", note: "The required station, tools, and progression gates need a dated in-game check.", status: "Needs gameplay check" },
          { item: "Coordinates and route", note: "No coordinates or fastest route are published here yet.", status: "Needs gameplay check" },
        ],
        partsAsideTitle: "Common mistakes",
        partsAsideItems: [
          "Do not assume the item is mandatory before its function is verified.",
          "Do not publish coordinates copied from a changing Early Access route.",
          "Do not mix source-reported notes with S2GuideHub-verified data.",
        ],
        routeEyebrow: "Optimized route",
        routeTitle: "Route structure for the first verification pass",
        routeIntro: [
          "The route should be built only after the unlock source and prerequisite chain are confirmed.",
        ],
        routeSteps: [
          { title: "Confirm purpose", body: "Test what the Feedback Resonator actually changes for navigation, scanning, or progression." },
          { title: "Identify prerequisites", body: "Record the station, tools, prior unlocks, and survival setup required before chasing it." },
          { title: "Gather evidence", body: "Collect official notes, player evidence, and in-game observations without turning them into coordinates yet." },
          { title: "Run the route", body: "Check whether the trip can be combined with safer early-mid objectives." },
          { title: "Publish log", body: "Add coordinates only with build version, date, source, and correction notes." },
        ],
        risksEyebrow: "Risks and extras",
        risksTitle: "Risks to avoid",
        risks: [
          "Overstating utility before the item function is tested.",
          "Sending players into a route without confirmed oxygen, depth, or return assumptions.",
          "Treating Early Access locations as stable after a patch.",
        ],
        extrasTitle: "Possible route extras",
        extras: [
          "Nearby scans or materials can be added only after the same trip is verified.",
          "If the route overlaps a safe base or beacon setup, record it as a route benefit.",
          "If it improves co-op navigation, add a short team-use note.",
        ],
        verificationEyebrow: "Verification",
        verificationTitle: "What counts as publishable data",
        verificationIntro: [
          "This page should become coordinate-level only after S2GuideHub checks the current build directly.",
        ],
        sources: officialSources.en,
        nextTitle: "Next verification pass",
        nextBody: [
          "Confirm the unlock function, acquisition method, recipe, route risk, and whether it changes the priority order of other Featured Unlocks.",
        ],
      },
      zh: {
        ...common.zh,
        heroEyebrow: "蓝图图谱物品页",
        title: "Feedback Resonator",
        deck: [
          "这是 Feedback Resonator 的来源意识型规划页。页面先说明它可能为什么重要，但精确位置、坐标、材料数量和路线耗时全部标为待实测。",
        ],
        summaryAria: "Feedback Resonator 状态总览",
        summaryItems: [
          { label: "推荐阶段", value: "早中期" },
          { label: "价值点", value: "工具、信号逻辑、路线顺序" },
          { label: "路线难度", value: "中" },
          { label: "风险等级", value: "中" },
          { label: "当前状态", value: "待实测" },
          { label: "最后检查", value: "2026-05-30" },
        ],
        summaryEyebrow: "总览",
        summaryTitle: "先把它当作工具类候选项，而不是已完成路线",
        summaryBody: [
          "Feedback Resonator 值得追踪，是因为工具类解锁可能改变后续目标的发现、排序或验证方式。它的具体功能还需要 S2GuideHub 实测后，页面才能写更强的路线判断。",
          "当前页面先作为高质量模板：测试什么价值、确认什么需求、避免什么路线假设，以及坐标公开前必须记录哪些证据。",
        ],
        relatedLinks: [
          { href: "tadpole-vehicle.html", label: "Tadpole Vehicle" },
          { href: "improved-fins.html", label: "Improved Fins" },
        ],
        statusTitle: "信息可靠度",
        statusItems: [
          { term: "已知方向", description: "第一批 Blueprint Atlas 解锁项里的工具或进度候选项。" },
          { term: "待核查", description: "具体功能、前置条件、制作材料和获取方式。" },
          { term: "暂不发布", description: "坐标、路线耗时、材料总量和生物压力判断。" },
        ],
        valueEyebrow: "玩家价值",
        valueTitle: "为什么它属于 Featured Unlocks",
        valueIntro: [
          "图谱应该优先收录会改变后续多个决策的解锁项。如果 Feedback Resonator 影响信号读取、侦察或目标发现，它的价值可能高于配方成本本身。",
        ],
        valueCards: [
          { title: "路线排序", body: "可能影响玩家在深入探索前应该先核查哪些目标。" },
          { title: "信号清晰度", body: "如果它能减少目标判断的不确定性，就值得单独测试。" },
          { title: "低噪音规划", body: "页面需要把工具用途和未验证地图说法分开。" },
          { title: "联机协作", body: "如果它影响共享导航，队伍需要知道谁携带或使用。" },
        ],
        partsEyebrow: "所需部件",
        partsTitle: "需求目前故意不写死",
        partsIntro: [
          "下面不是配方表，而是第一次实测时要确认的清单。",
        ],
        partsRows: [
          { item: "解锁来源", note: "具体是扫描、拾取还是蓝图来源，本站尚未实测。", status: "待实测" },
          { item: "制作材料", note: "材料名和数量要等当前版本核查后再发布。", status: "待实测" },
          { item: "制作站或前置条件", note: "所需制作站、工具和进度门槛需要带日期的实机核查。", status: "待实测" },
          { item: "坐标和路线", note: "这里暂不发布坐标或最快路线。", status: "待实测" },
        ],
        partsAsideTitle: "常见错误",
        partsAsideItems: [
          "在功能确认前就默认它是必拿物品。",
          "直接复制抢先体验路线坐标。",
          "把外部来源说法和本站实测混在一起。",
        ],
        routeEyebrow: "推荐路线",
        routeTitle: "第一次实测时的路线结构",
        routeIntro: [
          "只有在获取方式和前置链确认后，才应该整理正式路线。",
        ],
        routeSteps: [
          { title: "确认用途", body: "测试 Feedback Resonator 对导航、扫描或进度到底改变了什么。" },
          { title: "确认前置", body: "记录需要的制作站、工具、前置解锁和生存准备。" },
          { title: "收集证据", body: "整理官方说明、玩家证据和实机观察，但先不写坐标。" },
          { title: "实跑路线", body: "检查这趟是否能和安全的早中期目标合并。" },
          { title: "发布记录", body: "只有带版本、日期、来源和修正说明时才补坐标。" },
        ],
        risksEyebrow: "风险与顺路收益",
        risksTitle: "需要避免的风险",
        risks: [
          "在功能实测前夸大它的用途。",
          "没有确认氧气、深度或返程假设就引导玩家出发。",
          "补丁后仍把抢先体验位置当作稳定数据。",
        ],
        extrasTitle: "可能的顺路收益",
        extras: [
          "附近扫描点或材料必须和同一路线一起实测后再加入。",
          "如果路线经过安全基地或信标点，可以记录为路线收益。",
          "如果它改善联机导航，再补一条队伍使用建议。",
        ],
        verificationEyebrow: "信息可靠度",
        verificationTitle: "什么信息可以公开",
        verificationIntro: [
          "只有 S2GuideHub 在当前版本直接核查后，这个页面才应该进入坐标级攻略。",
        ],
        sources: officialSources.zh,
        nextTitle: "下一次实测",
        nextBody: [
          "确认功能、获取方式、配方、路线风险，以及它是否会改变其他 Featured Unlocks 的优先级。",
        ],
      },
    },
  },

  "tadpole-haul-chassis": {
    content: {
      en: {
        ...common.en,
        heroEyebrow: "Blueprint Atlas item guide",
        title: "Tadpole Haul Chassis",
        deck: [
          "A vehicle-assembly planning page for the Tadpole Haul Chassis. The page is designed to prevent wasted trips by separating confirmed prerequisites from unverified component and route claims.",
        ],
        summaryAria: "Tadpole Haul Chassis status summary",
        summaryItems: [
          { label: "Recommended stage", value: "Mid game" },
          { label: "Value point", value: "Vehicle assembly, storage planning, route efficiency" },
          { label: "Route difficulty", value: "Medium" },
          { label: "Risk level", value: "Medium" },
          { label: "Current status", value: "Needs gameplay check" },
          { label: "Last checked", value: "2026-05-30" },
        ],
        summaryEyebrow: "Summary",
        summaryTitle: "Use this page to organize the vehicle build chain",
        summaryBody: [
          "Vehicle-adjacent unlocks are expensive when the player chases them without knowing prerequisites, storage needs, and crafting chain order. This page keeps the Tadpole Haul Chassis in the Atlas while marking the detailed route as unverified.",
          "No exact fragment locations, coordinates, route timing, or material totals are published here yet.",
        ],
        relatedLinks: [
          { href: "tadpole-vehicle.html", label: "Tadpole Vehicle" },
          { href: "tadpole-depth-module-mk-i.html", label: "Depth Module MK I" },
        ],
        statusTitle: "Verification status",
        statusItems: [
          { term: "Known direction", description: "Vehicle assembly candidate tied to Tadpole-route planning." },
          { term: "Needs check", description: "Blueprint source, required components, station needs, and route order." },
          { term: "Not published here", description: "Exact coordinates, final recipe, and fastest assembly route." },
        ],
        valueEyebrow: "Player value",
        valueTitle: "Why chassis planning matters",
        valueIntro: [
          "The value of a chassis guide is not just the item. It is the checklist that stops a player from traveling to a vehicle objective before their base, crafting station, storage, or prerequisite chain is ready.",
        ],
        valueCards: [
          { title: "Build readiness", body: "Clarifies when the player should start vehicle assembly instead of gathering random materials." },
          { title: "Wasted-trip reduction", body: "Groups prerequisites before long-distance travel begins." },
          { title: "Co-op logistics", body: "Gives teams a shared material and base-work target." },
          { title: "Upgrade pathway", body: "Connects naturally to Tadpole Vehicle and depth-module pages." },
        ],
        partsEyebrow: "Required parts",
        partsTitle: "Chassis requirements to verify",
        partsIntro: [
          "This page intentionally avoids final component claims until they are checked in the live build.",
        ],
        partsRows: [
          { item: "Chassis blueprint source", note: "Scan or acquisition source is not verified by S2GuideHub.", status: "Needs gameplay check" },
          { item: "Component list", note: "Every component and quantity must be confirmed in the current Early Access build.", status: "Needs gameplay check" },
          { item: "Station and base needs", note: "Confirm whether any dock, fabricator, or clearance requirement blocks assembly.", status: "Needs gameplay check" },
          { item: "Route location", note: "No biome, landmark, or coordinate claim is published here yet.", status: "Needs gameplay check" },
        ],
        partsAsideTitle: "Common mistakes",
        partsAsideItems: [
          "Starting the chassis route before the vehicle build chain is understood.",
          "Gathering bulky components without knowing storage and return needs.",
          "Assuming a chassis route is safe because a final vehicle page exists.",
        ],
        routeEyebrow: "Optimized route",
        routeTitle: "Assembly route structure before coordinates",
        routeIntro: [
          "The first route pass should confirm prerequisites before sending players toward the chassis objective.",
        ],
        routeSteps: [
          { title: "Check prerequisites", body: "List required tools, stations, base rooms, and any prior Tadpole-related unlocks." },
          { title: "Confirm blueprint source", body: "Verify how the chassis is unlocked and how many scans or steps are required." },
          { title: "Plan component storage", body: "Group high-volume materials and decide whether a return trip or forward base is needed." },
          { title: "Run safe stop order", body: "Test the least risky route before adding locations to the public page." },
          { title: "Connect next unlock", body: "Document how this page feeds into Tadpole Vehicle or depth-module progression." },
        ],
        risksEyebrow: "Risks and extras",
        risksTitle: "Risks to avoid",
        risks: [
          "Publishing component quantities before checking the current build.",
          "Implying exact vehicle assembly order when station requirements are still unclear.",
          "Letting a mid-game vehicle route look like a beginner route.",
        ],
        extrasTitle: "Possible route extras",
        extras: [
          "Nearby base setup materials can be added after route verification.",
          "If the route overlaps Tadpole Vehicle preparation, link both pages clearly.",
          "If co-op storage rules help the route, add a team checklist later.",
        ],
        verificationEyebrow: "Verification",
        verificationTitle: "Chassis data must stay version-aware",
        verificationIntro: [
          "This page should graduate from template to walkthrough only after the acquisition method and build chain are confirmed.",
        ],
        sources: officialSources.en,
        nextTitle: "Next verification pass",
        nextBody: [
          "Confirm blueprint source, component list, station requirements, route assumptions, and whether it should be chased before or after the main Tadpole Vehicle page.",
        ],
      },
      zh: {
        ...common.zh,
        heroEyebrow: "蓝图图谱物品页",
        title: "Tadpole Haul Chassis",
        deck: [
          "这是 Tadpole Haul Chassis 的载具组装规划页。页面目标是把已确认前置和未验证组件、路线说法分开，减少玩家白跑。",
        ],
        summaryAria: "Tadpole Haul Chassis 状态总览",
        summaryItems: [
          { label: "推荐阶段", value: "中期" },
          { label: "价值点", value: "载具组装、储物规划、路线效率" },
          { label: "路线难度", value: "中" },
          { label: "风险等级", value: "中" },
          { label: "当前状态", value: "待实测" },
          { label: "最后检查", value: "2026-05-30" },
        ],
        summaryEyebrow: "总览",
        summaryTitle: "用这个页面整理载具建造链",
        summaryBody: [
          "和载具相关的解锁，如果前置、储物和制作链没弄清楚，最容易让玩家浪费远距离旅行。这个页面保留 Tadpole Haul Chassis 在图谱中的位置，但细节路线仍标为未验证。",
          "这里暂不发布精确碎片位置、坐标、路线耗时或材料总量。",
        ],
        relatedLinks: [
          { href: "tadpole-vehicle.html", label: "Tadpole Vehicle" },
          { href: "tadpole-depth-module-mk-i.html", label: "Depth Module MK I" },
        ],
        statusTitle: "信息可靠度",
        statusItems: [
          { term: "已知方向", description: "和 Tadpole 路线规划相关的载具组装候选项。" },
          { term: "待核查", description: "蓝图来源、所需组件、制作站需求和路线顺序。" },
          { term: "暂不发布", description: "精确坐标、最终配方和最快组装路线。" },
        ],
        valueEyebrow: "玩家价值",
        valueTitle: "为什么底盘规划重要",
        valueIntro: [
          "底盘页的价值不只是物品本身，而是让玩家在基地、制作站、储物和前置链准备好之前，不要贸然追载具目标。",
        ],
        valueCards: [
          { title: "建造准备", body: "说明什么时候应该开始载具组装，而不是随机囤材料。" },
          { title: "减少白跑", body: "在远行前先合并前置需求。" },
          { title: "联机后勤", body: "给队伍一个共享材料和基地建设目标。" },
          { title: "升级路径", body: "自然连接 Tadpole Vehicle 和深度模块页面。" },
        ],
        partsEyebrow: "所需部件",
        partsTitle: "需要实测的底盘需求",
        partsIntro: [
          "在当前版本实测前，本页故意不写死最终组件。",
        ],
        partsRows: [
          { item: "底盘蓝图来源", note: "扫描或获取来源本站尚未实测。", status: "待实测" },
          { item: "组件清单", note: "每个组件和数量都要在当前抢先体验版本中确认。", status: "待实测" },
          { item: "制作站和基地需求", note: "需要确认是否有停靠、制作器或空间限制。", status: "待实测" },
          { item: "路线位置", note: "暂不发布生物群系、地标或坐标说法。", status: "待实测" },
        ],
        partsAsideTitle: "常见错误",
        partsAsideItems: [
          "在载具建造链没弄清前就开始追底盘。",
          "不知道储物和返程需求就收集大体积组件。",
          "因为已有最终载具页，就默认底盘路线安全。",
        ],
        routeEyebrow: "推荐路线",
        routeTitle: "坐标公开前的组装路线结构",
        routeIntro: [
          "第一次路线实测应该先确认前置条件，再让玩家朝底盘目标出发。",
        ],
        routeSteps: [
          { title: "检查前置", body: "列出需要的工具、制作站、基地房间和 Tadpole 相关前置。" },
          { title: "确认蓝图来源", body: "核查底盘如何解锁，需要多少次扫描或步骤。" },
          { title: "规划组件储物", body: "合并大体积材料，判断是否需要返程或前置基地。" },
          { title: "实跑安全顺序", body: "先测试风险最低的停靠顺序，再公开位置。" },
          { title: "连接下一项", body: "记录它如何衔接 Tadpole Vehicle 或深度模块进度。" },
        ],
        risksEyebrow: "风险与顺路收益",
        risksTitle: "需要避免的风险",
        risks: [
          "在当前版本核查前发布组件数量。",
          "制作站需求还不清楚时暗示精确组装顺序。",
          "让中期载具路线看起来像新手路线。",
        ],
        extrasTitle: "可能的顺路收益",
        extras: [
          "附近基地材料必须等路线实测后再加入。",
          "如果路线和 Tadpole Vehicle 准备重叠，需要清楚互链。",
          "如果联机储物规则能提升效率，后续补队伍清单。",
        ],
        verificationEyebrow: "信息可靠度",
        verificationTitle: "底盘数据必须跟版本绑定",
        verificationIntro: [
          "只有获取方式和建造链确认后，本页才应该从模板升级成完整攻略。",
        ],
        sources: officialSources.zh,
        nextTitle: "下一次实测",
        nextBody: [
          "确认蓝图来源、组件清单、制作站要求、路线假设，以及它应该在 Tadpole Vehicle 前还是后追。",
        ],
      },
    },
  },

  "tadpole-vehicle": {
    content: {
      en: {
        ...common.en,
        heroEyebrow: "Blueprint Atlas item guide",
        title: "Tadpole Vehicle",
        deck: [
          "A route-first guide for deciding when the Tadpole is worth chasing, what is currently source-reported, and what still needs S2GuideHub gameplay verification before exact coordinates go public.",
        ],
        summaryAria: "Tadpole Vehicle status summary",
        summaryItems: [
          { label: "Recommended stage", value: "Mid game" },
          { label: "Value point", value: "Range, oxygen margin, co-op logistics" },
          { label: "Route difficulty", value: "High" },
          { label: "Risk level", value: "High" },
          { label: "Current status", value: "Source-reported" },
          { label: "Last checked", value: "2026-05-30" },
        ],
        summaryEyebrow: "Summary",
        summaryTitle: "Prioritize the Tadpole once basic survival loops are stable",
        summaryBody: [
          "The Tadpole changes how a player thinks about distance, oxygen safety, hostile water, and return planning. Official store copy names the Tadpole as the submersible used to traverse biomes, while the Early Access roadmap makes clear that vehicles and related systems may continue changing.",
          "Treat this page as a complete route framework, not a final coordinate walkthrough. The public route should become coordinate-level only after S2GuideHub checks the fragment path, build chain, and material counts in the current game build.",
        ],
        relatedLinks: [
          { href: "improved-fins.html", label: "Improved Fins" },
          { href: "tadpole-haul-chassis.html", label: "Tadpole Haul Chassis" },
          { href: "tadpole-depth-module-mk-i.html", label: "Depth Module MK I" },
        ],
        statusTitle: "Verification status",
        statusItems: [
          { term: "Officially confirmed", description: "Tadpole submersible exists; Subnautica 2 is active Early Access." },
          { term: "Source-reported", description: "Fragment scan count, base setup, and material chain." },
          { term: "Not yet published here", description: "Exact coordinates, fastest route timing, and final component checklist." },
        ],
        valueEyebrow: "Player value",
        valueTitle: "Why this unlock deserves a flagship page",
        valueIntro: [
          "Tadpole planning has several high-value decisions packed into one route: whether the player is ready, whether the fragment route is safe, whether the base build chain is worth the cost, and what the vehicle unlock enables next.",
        ],
        valueCards: [
          { title: "Travel range", body: "Turns some long swims into planned vehicle routes once the build is stable." },
          { title: "Safety margin", body: "Creates a stronger return plan for deeper or more hostile water." },
          { title: "Co-op routing", body: "Gives teams a clearer shared objective and base logistics checkpoint." },
          { title: "Upgrade path", body: "Connects naturally to later depth, efficiency, chassis, and storage pages." },
        ],
        partsEyebrow: "Required parts",
        partsTitle: "Source-reported requirements to verify",
        partsIntro: [
          "The table below intentionally separates what external guide sources report from what S2GuideHub has verified.",
        ],
        partsRows: [
          { item: "Tadpole blueprint", note: "PC Gamer reports that three Tadpole fragment scans are required.", status: "Source-reported" },
          { item: "Build station", note: "PC Gamer reports a Moonpool, Tadpole Dock, and Vehicle Fabricator setup.", status: "Source-reported" },
          { item: "Crafting materials", note: "PC Gamer reports titanium ingots, glass, a system chip, and a power cell for the final Tadpole craft.", status: "Source-reported" },
          { item: "Exact route", note: "Coordinate and stop-order details stay unpublished here until S2GuideHub checks them in-game.", status: "Needs gameplay check" },
        ],
        partsAsideTitle: "Common mistakes",
        partsAsideItems: [
          "Chasing distant fragments before oxygen safety is comfortable.",
          "Building the base setup without enough clearance for vehicle docking.",
          "Crafting the vehicle without planning repair and emergency power.",
          "Treating Early Access coordinates as permanent after patches.",
        ],
        routeEyebrow: "Optimized route",
        routeTitle: "Recommended route structure before coordinates",
        routeIntro: [
          "Use this order for the first verified route pass. Each stop needs a source note and a last-checked date before it becomes a finished walkthrough.",
        ],
        routeSteps: [
          { title: "Prepare", body: "Bring the Scanner, a strong oxygen margin, a beacon habit, spare storage, and a return rule. The Tadpole route is not a first-dive route." },
          { title: "Scan fragments", body: "Player-guide sources currently report that three Tadpole fragment scans unlock the blueprint. S2GuideHub still needs to verify the safest stop order." },
          { title: "Build the base chain", body: "Source-reported setup includes a Moonpool, Tadpole Dock clearance, and Vehicle Fabricator. Confirm space and materials before committing." },
          { title: "Craft and test", body: "Craft the Tadpole only after the material list is checked against the live build. Run a short shakedown trip before pushing deeper." },
          { title: "Log changes", body: "Record build version, fragment route, component counts, and any patch-sensitive notes for future updates." },
        ],
        risksEyebrow: "Risks and extras",
        risksTitle: "Risks to avoid",
        risks: [
          "Assuming source-reported coordinates are still safe after a patch.",
          "Starting the route before basic survival, oxygen, and return rules are stable.",
          "Building vehicle infrastructure without confirming every required station and material.",
        ],
        extrasTitle: "Easy benefits to combine later",
        extras: [
          "Improved Fins may be worth checking before repeated long swims around vehicle objectives.",
          "If a safe base location overlaps the route, add it after verification.",
          "Co-op teams should split scanning, material gathering, and base setup only after the build chain is confirmed.",
        ],
        verificationEyebrow: "Verification",
        verificationTitle: "Sources checked for this guide",
        verificationIntro: [
          "The Tadpole page uses official context plus third-party guide notes, but exact route claims still need S2GuideHub gameplay verification.",
        ],
        sources: [
          officialSources.en[0],
          officialSources.en[1],
          {
            label: "PC Gamer Tadpole guide",
            href: "https://www.pcgamer.com/games/survival-crafting/subnautica-2-tadpole-scan-locations/",
            note: "Third-party guide used for source-reported scan count and build-chain notes.",
          },
        ],
        nextTitle: "Next verification pass",
        nextBody: [
          "Add the exact in-game build version, verified fragment stop order, confirmed material totals, and a dated correction log.",
        ],
      },
      zh: {
        ...common.zh,
        heroEyebrow: "蓝图图谱物品页",
        title: "Tadpole Vehicle",
        deck: [
          "这是用于判断什么时候该追 Tadpole 的路线优先页面：当前有哪些外部来源说法，哪些内容还需要 S2GuideHub 实测后才能公开坐标。",
        ],
        summaryAria: "Tadpole Vehicle 状态总览",
        summaryItems: [
          { label: "推荐阶段", value: "中期" },
          { label: "价值点", value: "航程、氧气余量、联机后勤" },
          { label: "路线难度", value: "高" },
          { label: "风险等级", value: "高" },
          { label: "当前状态", value: "来源报告，待实测" },
          { label: "最后检查", value: "2026-05-30" },
        ],
        summaryEyebrow: "总览",
        summaryTitle: "基础生存循环稳定后，再优先考虑 Tadpole",
        summaryBody: [
          "Tadpole 会改变玩家对距离、氧气安全、危险水域和返程规划的判断。官方商店文案提到 Tadpole 是用于穿越生物群系的潜航器，而抢先体验路线图也说明载具和相关系统后续仍可能变化。",
          "请把这个页面当作完整路线框架，而不是最终坐标攻略。只有本站实测当前版本的碎片路径、建造链和材料数量后，才会进入坐标级路线。",
        ],
        relatedLinks: [
          { href: "improved-fins.html", label: "Improved Fins" },
          { href: "tadpole-haul-chassis.html", label: "Tadpole Haul Chassis" },
          { href: "tadpole-depth-module-mk-i.html", label: "Depth Module MK I" },
        ],
        statusTitle: "信息可靠度",
        statusItems: [
          { term: "官方确认", description: "Tadpole 潜航器存在；Subnautica 2 仍处于抢先体验。" },
          { term: "外部来源报告", description: "碎片扫描数量、基地设置和材料链。" },
          { term: "本站暂不发布", description: "精确坐标、最快路线耗时和最终组件清单。" },
        ],
        valueEyebrow: "玩家价值",
        valueTitle: "为什么它值得做成旗舰页面",
        valueIntro: [
          "Tadpole 路线把多个高价值决策集中在一起：玩家是否准备好、碎片路线是否安全、基地建造链是否值得投入，以及载具解锁后能打开什么。",
        ],
        valueCards: [
          { title: "旅行半径", body: "当建造稳定后，一些长距离游泳可以变成有计划的载具路线。" },
          { title: "安全余量", body: "为更深或更危险水域提供更强的返程计划。" },
          { title: "联机路线", body: "给队伍一个明确的共享目标和基地后勤节点。" },
          { title: "升级路径", body: "自然连接后续深度、效率、底盘和储物页面。" },
        ],
        partsEyebrow: "所需部件",
        partsTitle: "需要核查的外部来源需求",
        partsIntro: [
          "下表故意把外部攻略说法和 S2GuideHub 已验证内容分开。",
        ],
        partsRows: [
          { item: "Tadpole 蓝图", note: "PC Gamer 报告需要扫描三个 Tadpole 碎片。", status: "来源报告" },
          { item: "建造设施", note: "PC Gamer 报告需要 Moonpool、Tadpole Dock 和 Vehicle Fabricator 相关设置。", status: "来源报告" },
          { item: "制作材料", note: "PC Gamer 报告最终制作涉及 titanium ingots、glass、system chip 和 power cell。", status: "来源报告" },
          { item: "精确路线", note: "坐标和停靠顺序要等本站实测后再公开。", status: "待实测" },
        ],
        partsAsideTitle: "常见错误",
        partsAsideItems: [
          "氧气安全还不稳就追远距离碎片。",
          "基地空间不足就开始搭载具设施。",
          "制作载具前没有规划维修和应急电力。",
          "把抢先体验坐标当作补丁后仍永久有效。",
        ],
        routeEyebrow: "推荐路线",
        routeTitle: "公开坐标前的推荐路线结构",
        routeIntro: [
          "第一次实测路线可以按这个顺序整理。每个停靠点都需要来源说明和最后检查日期，才能成为正式攻略。",
        ],
        routeSteps: [
          { title: "准备", body: "带上 Scanner，保证氧气余量，养成放信标习惯，预留储物空间，并设定返航规则。Tadpole 不是第一次下潜路线。" },
          { title: "扫描碎片", body: "外部玩家攻略目前报告三个 Tadpole 碎片可解锁蓝图。本站仍需实测最安全的停靠顺序。" },
          { title: "搭建基地链", body: "外部来源提到 Moonpool、Tadpole Dock 空间和 Vehicle Fabricator。投入前要确认空间和材料。" },
          { title: "制作并测试", body: "只有材料表和当前版本一致后再制作 Tadpole，并先跑短距离测试。" },
          { title: "记录变化", body: "记录版本、碎片路线、组件数量和受补丁影响的备注。" },
        ],
        risksEyebrow: "风险与顺路收益",
        risksTitle: "需要避免的风险",
        risks: [
          "把外部来源坐标当作补丁后仍安全。",
          "基础生存、氧气和返程规则不稳定就出发。",
          "没有确认每个制作站和材料就开始建载具设施。",
        ],
        extrasTitle: "后续可合并的顺路收益",
        extras: [
          "围绕载具目标反复长距离游泳前，Improved Fins 可能值得先核查。",
          "如果路线经过安全基地点，实测后再加入。",
          "联机队伍应在建造链确认后再分配扫描、采集和基地建设。",
        ],
        verificationEyebrow: "信息可靠度",
        verificationTitle: "本页检查过的来源",
        verificationIntro: [
          "Tadpole 页使用官方背景和第三方攻略说明，但精确路线仍需要 S2GuideHub 实测。",
        ],
        sources: [
          officialSources.zh[0],
          officialSources.zh[1],
          {
            label: "PC Gamer Tadpole guide",
            href: "https://www.pcgamer.com/games/survival-crafting/subnautica-2-tadpole-scan-locations/",
            note: "第三方攻略，用于记录扫描数量和建造链的来源说法。",
          },
        ],
        nextTitle: "下一次实测",
        nextBody: [
          "补充当前游戏版本、已验证碎片停靠顺序、确认后的材料总量和带日期的修正记录。",
        ],
      },
    },
  },

  "improved-fins": {
    content: {
      en: {
        ...common.en,
        heroEyebrow: "Blueprint Atlas item guide",
        title: "Improved Fins",
        deck: [
          "A source-aware route page for deciding when the Improved Fins are worth chasing, what outside guides currently report, and which route claims still need S2GuideHub gameplay verification.",
        ],
        summaryAria: "Improved Fins status summary",
        summaryItems: [
          { label: "Recommended stage", value: "Mid game" },
          { label: "Value point", value: "Swim speed, oxygen efficiency, escape margin" },
          { label: "Route difficulty", value: "Medium" },
          { label: "Risk level", value: "Medium" },
          { label: "Current status", value: "Source-reported" },
          { label: "Last checked", value: "2026-05-30" },
        ],
        summaryEyebrow: "Summary",
        summaryTitle: "Get Improved Fins when your deeper route is already open",
        summaryBody: [
          "Improved Fins are a strong Blueprint Atlas candidate because movement speed affects almost every later dive: oxygen margin, collection loops, creature escapes, and the time it takes to return to the Tadpole when a route gets messy.",
          "The current source picture points to a deeper mid-game route, but S2GuideHub is keeping exact coordinates and fastest-stop order unpublished until the route is checked in the current Early Access build.",
        ],
        relatedLinks: [
          { href: "tadpole-vehicle.html", label: "Tadpole Vehicle" },
          { href: "tadpole-depth-module-mk-i.html", label: "Depth Module MK I" },
        ],
        statusTitle: "Verification status",
        statusItems: [
          { term: "Official context", description: "Subnautica 2 is in active Early Access, and future resources, tools, vehicles, and systems may change." },
          { term: "Source-reported", description: "Scan count, deeper route context, risk notes, and crafting inputs." },
          { term: "Not yet published here", description: "Exact coordinates, fastest route timing, and final S2GuideHub material checklist." },
        ],
        valueEyebrow: "Player value",
        valueTitle: "Why this unlock should be early in the Atlas",
        valueIntro: [
          "Tadpole Vehicle changes travel scale. Improved Fins change player movement inside every route. That makes this upgrade a good page before deeper vehicle-module guides.",
        ],
        valueCards: [
          { title: "Oxygen efficiency", body: "Faster swimming can reduce time spent between air sources, the Tadpole, and objective stops." },
          { title: "Escape margin", body: "Movement upgrades matter most when a creature encounter turns a clean route into a retreat." },
          { title: "Collection loops", body: "Repeated material trips become less punishing when the player moves faster in tight spaces." },
          { title: "Route combos", body: "The same trip may overlap with story objectives, materials, and later Blueprint Atlas checks." },
        ],
        partsEyebrow: "Required parts",
        partsTitle: "Source-reported requirements to verify",
        partsIntro: [
          "Improved Fins are useful enough to publish as an Atlas target now, but every route detail below stays labeled until S2GuideHub checks it directly.",
        ],
        partsRows: [
          { item: "Blueprint scans", note: "GamesRadar and GAMES.GG report that three Improved Fins scan targets unlock the blueprint.", status: "Source-reported" },
          { item: "Route access", note: "External guides place the useful route after deeper progression. Exact gating stays unverified here.", status: "Source-reported" },
          { item: "Crafting inputs", note: "GAMES.GG reports Basic Fins, Fiber Mesh, and Conduit Crystals as current recipe inputs.", status: "Source-reported" },
          { item: "Exact stop order", note: "Coordinates and route timing stay unpublished here until the current build is checked in-game.", status: "Needs gameplay check" },
        ],
        partsAsideTitle: "Common mistakes",
        partsAsideItems: [
          "Chasing Improved Fins before the route is naturally open.",
          "Diving into a deeper scan area without a strong oxygen and return plan.",
          "Assuming third-party coordinates are still correct after Early Access patches.",
          "Forgetting that crafting ingredients may be the real blocker after scans are complete.",
        ],
        routeEyebrow: "Optimized route",
        routeTitle: "Recommended route structure before coordinates",
        routeIntro: [
          "This is the practical order for the first S2GuideHub verification pass. It keeps the page useful without pretending that external coordinates are already our own confirmed route.",
        ],
        routeSteps: [
          { title: "Confirm access", body: "Do not treat this as a first-hour upgrade. Verify which progression step naturally opens the scan route." },
          { title: "Prepare safety", body: "Bring Scanner, oxygen confidence, return planning, and repair readiness if vehicle travel is involved." },
          { title: "Scan the cluster", body: "External guides report multiple scan targets. Verify the least risky order before publishing coordinates." },
          { title: "Craft and compare", body: "Check the live recipe, craft the upgrade, and record whether movement gain changes route priority." },
          { title: "Log changes", body: "Record build version, scan count, route assumptions, ingredient totals, and patch-sensitive notes." },
        ],
        risksEyebrow: "Risks and extras",
        risksTitle: "Risks to avoid",
        risks: [
          "Presenting a deeper route as if it were beginner-safe.",
          "Copying coordinates without a current-build check.",
          "Publishing creature or hazard pressure as fact before S2GuideHub observes it.",
        ],
        extrasTitle: "Easy benefits to combine later",
        extras: [
          "If the route overlaps other scan targets, add them only after the same run confirms them.",
          "If the upgrade noticeably changes Tadpole-route safety, link the Tadpole page with a dated note.",
          "If specific crafting blockers slow the route, promote them into the required-parts table.",
        ],
        verificationEyebrow: "Verification",
        verificationTitle: "Sources checked for this guide",
        verificationIntro: [
          "This page uses official Early Access context and source-reported guide data, but final route claims remain pending.",
        ],
        sources: [
          officialSources.en[0],
          officialSources.en[1],
          {
            label: "GamesRadar Improved Fins guide",
            href: "https://www.gamesradar.com/games/survival/subnautica-2-improved-fins/",
            note: "Third-party guide used for source-reported progression gating, scan count, route context, and risk notes.",
          },
          {
            label: "GAMES.GG Improved Fins guide",
            href: "https://games.gg/subnautica-2/guides/subnautica-2-all-improved-fins-fragment-locations/",
            note: "Third-party guide used for source-reported scan clustering, crafting inputs, and route notes.",
          },
        ],
        nextTitle: "Next verification pass",
        nextBody: [
          "Add the current game build, verified scan order, confirmed recipe, safety equipment recommendation, and a dated correction log.",
        ],
      },
      zh: {
        ...common.zh,
        heroEyebrow: "蓝图图谱物品页",
        title: "Improved Fins",
        deck: [
          "这是 Improved Fins 的来源意识型路线页：说明什么时候值得追、外部攻略目前怎么说，以及哪些路线判断还需要 S2GuideHub 实测。",
        ],
        summaryAria: "Improved Fins 状态总览",
        summaryItems: [
          { label: "推荐阶段", value: "中期" },
          { label: "价值点", value: "游速、氧气效率、撤退余量" },
          { label: "路线难度", value: "中" },
          { label: "风险等级", value: "中" },
          { label: "当前状态", value: "来源报告，待实测" },
          { label: "最后检查", value: "2026-05-30" },
        ],
        summaryEyebrow: "总览",
        summaryTitle: "当更深路线已经打开时，再追 Improved Fins",
        summaryBody: [
          "Improved Fins 是很强的图谱候选项，因为移动速度会影响几乎所有后续下潜：氧气余量、采集循环、遭遇后的撤退，以及路线混乱时回到 Tadpole 的时间。",
          "当前外部来源指向更深的中期路线，但本站在当前抢先体验版本实测前，不公开精确坐标和最快停靠顺序。",
        ],
        relatedLinks: [
          { href: "tadpole-vehicle.html", label: "Tadpole Vehicle" },
          { href: "tadpole-depth-module-mk-i.html", label: "Depth Module MK I" },
        ],
        statusTitle: "信息可靠度",
        statusItems: [
          { term: "官方背景", description: "Subnautica 2 仍在抢先体验，资源、工具、载具和系统后续可能变化。" },
          { term: "外部来源报告", description: "扫描数量、更深路线背景、风险提示和制作材料。" },
          { term: "本站暂不发布", description: "精确坐标、最快路线耗时和本站最终材料清单。" },
        ],
        valueEyebrow: "玩家价值",
        valueTitle: "为什么它应该较早进入图谱",
        valueIntro: [
          "Tadpole Vehicle 改变旅行尺度，Improved Fins 改变玩家在每条路线内的移动效率。因此它适合放在更深载具模块指南之前。",
        ],
        valueCards: [
          { title: "氧气效率", body: "更快游速可以减少在空气来源、Tadpole 和目标点之间消耗的时间。" },
          { title: "撤退余量", body: "当遭遇让原本干净的路线变成撤退时，移动升级最有价值。" },
          { title: "采集循环", body: "在狭窄区域反复拿材料时，更快移动会降低路线惩罚。" },
          { title: "路线合并", body: "同一趟可能与剧情目标、材料和后续图谱核查重叠。" },
        ],
        partsEyebrow: "所需部件",
        partsTitle: "需要核查的外部来源需求",
        partsIntro: [
          "Improved Fins 的价值足够先作为图谱目标发布，但每个路线细节都必须等本站实测。",
        ],
        partsRows: [
          { item: "蓝图扫描", note: "GamesRadar 和 GAMES.GG 报告需要三个 Improved Fins 扫描目标。", status: "来源报告" },
          { item: "路线开放", note: "外部攻略把有效路线放在更深进度之后。具体前置本站仍未确认。", status: "来源报告" },
          { item: "制作材料", note: "GAMES.GG 报告当前配方包含 Basic Fins、Fiber Mesh 和 Conduit Crystals。", status: "来源报告" },
          { item: "精确停靠顺序", note: "坐标和路线耗时要等当前版本实测后再公开。", status: "待实测" },
        ],
        partsAsideTitle: "常见错误",
        partsAsideItems: [
          "路线还没自然打开就追 Improved Fins。",
          "没有强氧气和返程计划就进入更深扫描区域。",
          "默认第三方坐标在抢先体验补丁后仍正确。",
          "扫描完成后忘记真正卡住进度的可能是制作材料。",
        ],
        routeEyebrow: "推荐路线",
        routeTitle: "公开坐标前的推荐路线结构",
        routeIntro: [
          "这是 S2GuideHub 第一次实测时的实用顺序。它让页面有用，但不会假装外部坐标已经是本站验证路线。",
        ],
        routeSteps: [
          { title: "确认开放", body: "不要把它当作第一小时升级。先实测哪一步进度会自然打开扫描路线。" },
          { title: "安全准备", body: "带 Scanner，确认氧气余量和返程规划；如果涉及载具旅行，还要准备维修。" },
          { title: "扫描目标", body: "外部攻略报告有多个扫描目标。公开坐标前先核查风险最低顺序。" },
          { title: "制作并比较", body: "核查当前配方，制作升级，并记录移动提升是否改变路线优先级。" },
          { title: "记录变化", body: "记录版本、扫描数量、路线假设、材料总量和补丁敏感备注。" },
        ],
        risksEyebrow: "风险与顺路收益",
        risksTitle: "需要避免的风险",
        risks: [
          "把更深路线写得像新手安全路线。",
          "没有当前版本实测就复制坐标。",
          "本站观察前就把生物或危险压力写成事实。",
        ],
        extrasTitle: "后续可合并的顺路收益",
        extras: [
          "如果路线重叠其他扫描目标，必须同趟实测确认后再加入。",
          "如果升级明显改变 Tadpole 路线安全性，要在 Tadpole 页加带日期的说明。",
          "如果某些制作材料才是真阻塞点，要提升到所需部件表。",
        ],
        verificationEyebrow: "信息可靠度",
        verificationTitle: "本页检查过的来源",
        verificationIntro: [
          "本页使用官方抢先体验背景和外部攻略数据，但最终路线判断仍待实测。",
        ],
        sources: [
          officialSources.zh[0],
          officialSources.zh[1],
          {
            label: "GamesRadar Improved Fins guide",
            href: "https://www.gamesradar.com/games/survival/subnautica-2-improved-fins/",
            note: "第三方攻略，用于记录进度门槛、扫描数量、路线背景和风险提示。",
          },
          {
            label: "GAMES.GG Improved Fins guide",
            href: "https://games.gg/subnautica-2/guides/subnautica-2-all-improved-fins-fragment-locations/",
            note: "第三方攻略，用于记录扫描聚集、制作材料和路线说明。",
          },
        ],
        nextTitle: "下一次实测",
        nextBody: [
          "补充当前游戏版本、已验证扫描顺序、确认配方、安全装备建议和带日期的修正记录。",
        ],
      },
    },
  },

  "tadpole-depth-module-mk-i": {
    content: {
      en: {
        ...common.en,
        heroEyebrow: "Blueprint Atlas item guide",
        title: "Tadpole Depth Module MK I",
        deck: [
          "A depth-progression planning page for the Tadpole Depth Module MK I. The page keeps route value clear while marking exact prerequisites, safe depth assumptions, and coordinates as Needs gameplay check.",
        ],
        summaryAria: "Tadpole Depth Module MK I status summary",
        summaryItems: [
          { label: "Recommended stage", value: "Mid game" },
          { label: "Value point", value: "Depth access, route expansion, vehicle progression" },
          { label: "Route difficulty", value: "High" },
          { label: "Risk level", value: "High" },
          { label: "Current status", value: "Needs gameplay check" },
          { label: "Last checked", value: "2026-05-30" },
        ],
        summaryEyebrow: "Summary",
        summaryTitle: "Depth modules should stay conservative until verified",
        summaryBody: [
          "Depth progression can unlock whole new route layers, but it is also one of the easiest places to mislead players. A wrong prerequisite, depth assumption, or vehicle dependency can turn a guide into a wasted or unsafe trip.",
          "This page is intentionally cautious. It explains the planning value and the verification checklist without publishing coordinates, exact depth bands, or route timing.",
        ],
        relatedLinks: [
          { href: "tadpole-vehicle.html", label: "Tadpole Vehicle" },
          { href: "tadpole-haul-chassis.html", label: "Tadpole Haul Chassis" },
          { href: "improved-fins.html", label: "Improved Fins" },
        ],
        statusTitle: "Verification status",
        statusItems: [
          { term: "Known direction", description: "Depth progression candidate linked to Tadpole vehicle routing." },
          { term: "Needs check", description: "Prerequisite unlocks, recipe, safe operating depth, and route access." },
          { term: "Not published here", description: "Coordinates, exact depth claims, final route timing, and hazard behavior." },
        ],
        valueEyebrow: "Player value",
        valueTitle: "Why depth access changes the route map",
        valueIntro: [
          "A depth module can change which biomes, resources, and blueprint objectives are realistic. That makes it high-value, but also patch-sensitive and dependent on confirmed vehicle assumptions.",
        ],
        valueCards: [
          { title: "Progression layer", body: "May open objectives that are not practical at the base Tadpole depth." },
          { title: "Route safety", body: "A correct depth plan reduces panic dives and forced retreats." },
          { title: "Vehicle dependency", body: "Keeps the module connected to the full Tadpole build chain." },
          { title: "Patch sensitivity", body: "Depth and vehicle tuning may change during Early Access, so dates matter." },
        ],
        partsEyebrow: "Required parts",
        partsTitle: "Depth-module requirements to verify",
        partsIntro: [
          "No final recipe or coordinates should be published until S2GuideHub confirms the current build.",
        ],
        partsRows: [
          { item: "Module blueprint source", note: "Exact scan, fragment, or unlock trigger is not verified by S2GuideHub.", status: "Needs gameplay check" },
          { item: "Vehicle prerequisite", note: "Confirm whether Tadpole Vehicle, chassis, dock, or another station must be ready first.", status: "Needs gameplay check" },
          { item: "Crafting inputs", note: "Material names and quantities are not finalized on this page.", status: "Needs gameplay check" },
          { item: "Depth and route assumptions", note: "No exact safe depth, biome, landmark, or coordinate claim is published yet.", status: "Needs gameplay check" },
        ],
        partsAsideTitle: "Common mistakes",
        partsAsideItems: [
          "Publishing exact depth claims before checking the current build.",
          "Assuming the module can be chased before the Tadpole chain is ready.",
          "Ignoring return safety because the item itself is a depth upgrade.",
          "Forgetting that Early Access patches can move requirements or change balance.",
        ],
        routeEyebrow: "Optimized route",
        routeTitle: "Depth route structure before coordinates",
        routeIntro: [
          "The first verified route should begin with readiness checks, not map travel.",
        ],
        routeSteps: [
          { title: "Confirm vehicle chain", body: "Verify Tadpole, dock, station, and prerequisite requirements before planning the module trip." },
          { title: "Confirm recipe", body: "Check live material requirements and whether any rare input changes the route priority." },
          { title: "Set depth rules", body: "Record safe operating assumptions and do not publish exact depth bands until observed." },
          { title: "Run route test", body: "Test the route with a clear turn-back point and no unverified hazard claims." },
          { title: "Update linked pages", body: "If the module changes Tadpole routing, update the vehicle and chassis pages with dated notes." },
        ],
        risksEyebrow: "Risks and extras",
        risksTitle: "Risks to avoid",
        risks: [
          "Treating a depth upgrade as permission to ignore oxygen, power, or return planning.",
          "Making creature behavior claims before observing the current build.",
          "Writing coordinates without build version and last-checked date.",
        ],
        extrasTitle: "Possible route extras",
        extras: [
          "If the module route overlaps vehicle upgrade materials, add them after verification.",
          "If it unlocks a safer return loop, document the before and after route difference.",
          "If another Featured Unlock becomes easier after this module, cross-link it with a dated note.",
        ],
        verificationEyebrow: "Verification",
        verificationTitle: "Depth claims need the highest evidence bar",
        verificationIntro: [
          "Depth, hazard, and vehicle-limit claims can affect whether a route is safe. This page keeps them pending until they are checked directly.",
        ],
        sources: officialSources.en,
        nextTitle: "Next verification pass",
        nextBody: [
          "Confirm prerequisite chain, recipe, acquisition method, safe depth assumptions, and which linked pages need route updates.",
        ],
      },
      zh: {
        ...common.zh,
        heroEyebrow: "蓝图图谱物品页",
        title: "Tadpole Depth Module MK I",
        deck: [
          "这是 Tadpole Depth Module MK I 的深度进度规划页。页面先保留路线价值，同时把精确前置、安全深度假设和坐标全部标为待实测。",
        ],
        summaryAria: "Tadpole Depth Module MK I 状态总览",
        summaryItems: [
          { label: "推荐阶段", value: "中期" },
          { label: "价值点", value: "深度进入、路线扩展、载具进度" },
          { label: "路线难度", value: "高" },
          { label: "风险等级", value: "高" },
          { label: "当前状态", value: "待实测" },
          { label: "最后检查", value: "2026-05-30" },
        ],
        summaryEyebrow: "总览",
        summaryTitle: "深度模块在实测前必须保守",
        summaryBody: [
          "深度进度可能打开整层新路线，但也是最容易误导玩家的地方。错误前置、深度假设或载具依赖，都会让攻略变成白跑甚至危险路线。",
          "所以本页故意谨慎：先说明规划价值和核查清单，不发布坐标、精确深度区间或路线耗时。",
        ],
        relatedLinks: [
          { href: "tadpole-vehicle.html", label: "Tadpole Vehicle" },
          { href: "tadpole-haul-chassis.html", label: "Tadpole Haul Chassis" },
          { href: "improved-fins.html", label: "Improved Fins" },
        ],
        statusTitle: "信息可靠度",
        statusItems: [
          { term: "已知方向", description: "和 Tadpole 载具路线相关的深度进度候选项。" },
          { term: "待核查", description: "前置解锁、配方、安全工作深度和路线开放条件。" },
          { term: "暂不发布", description: "坐标、精确深度判断、最终路线耗时和危险行为。" },
        ],
        valueEyebrow: "玩家价值",
        valueTitle: "为什么深度进入会改写路线图",
        valueIntro: [
          "深度模块可能改变哪些生物群系、资源和蓝图目标变得现实。因此它价值高，但也受补丁影响，并依赖已确认的载具假设。",
        ],
        valueCards: [
          { title: "进度层级", body: "可能打开基础 Tadpole 深度下不现实的目标。" },
          { title: "路线安全", body: "正确深度规划能减少慌乱下潜和被迫撤退。" },
          { title: "载具依赖", body: "让模块和完整 Tadpole 建造链保持连接。" },
          { title: "补丁敏感", body: "深度和载具平衡可能在抢先体验中变化，所以日期很重要。" },
        ],
        partsEyebrow: "所需部件",
        partsTitle: "需要实测的深度模块需求",
        partsIntro: [
          "在 S2GuideHub 确认当前版本前，不应该发布最终配方或坐标。",
        ],
        partsRows: [
          { item: "模块蓝图来源", note: "具体扫描、碎片或解锁触发，本站尚未实测。", status: "待实测" },
          { item: "载具前置", note: "需要确认 Tadpole Vehicle、底盘、Dock 或其他制作站是否必须先准备好。", status: "待实测" },
          { item: "制作材料", note: "本页尚不写死材料名称和数量。", status: "待实测" },
          { item: "深度和路线假设", note: "暂不发布精确安全深度、生物群系、地标或坐标说法。", status: "待实测" },
        ],
        partsAsideTitle: "常见错误",
        partsAsideItems: [
          "当前版本未核查就发布精确深度判断。",
          "默认 Tadpole 链没准备好也能追模块。",
          "因为目标是深度升级，就忽略返程安全。",
          "忘记抢先体验补丁可能移动需求或改变平衡。",
        ],
        routeEyebrow: "推荐路线",
        routeTitle: "坐标公开前的深度路线结构",
        routeIntro: [
          "第一条验证路线应该从准备检查开始，而不是直接跑地图。",
        ],
        routeSteps: [
          { title: "确认载具链", body: "在规划模块旅行前，先核查 Tadpole、Dock、制作站和前置需求。" },
          { title: "确认配方", body: "核查当前材料需求，以及是否有稀有输入会改变路线优先级。" },
          { title: "设定深度规则", body: "记录安全工作假设，但未观察前不公开精确深度区间。" },
          { title: "实跑路线", body: "用明确返航点测试路线，不写未验证危险说法。" },
          { title: "更新关联页", body: "如果模块改变 Tadpole 路线，要给载具和底盘页加带日期的备注。" },
        ],
        risksEyebrow: "风险与顺路收益",
        risksTitle: "需要避免的风险",
        risks: [
          "把深度升级当作可以忽略氧气、电力或返程规划。",
          "当前版本观察前就写生物行为判断。",
          "没有版本号和最后检查日期就写坐标。",
        ],
        extrasTitle: "可能的顺路收益",
        extras: [
          "如果模块路线和载具升级材料重叠，实测后再加入。",
          "如果它打开更安全返程循环，需要记录前后路线差异。",
          "如果另一个 Featured Unlock 因此更容易获取，要加带日期的互链说明。",
        ],
        verificationEyebrow: "信息可靠度",
        verificationTitle: "深度相关说法需要最高证据标准",
        verificationIntro: [
          "深度、危险和载具限制会影响路线是否安全。本页在直接实测前全部保持待核查。",
        ],
        sources: officialSources.zh,
        nextTitle: "下一次实测",
        nextBody: [
          "确认前置链、配方、获取方式、安全深度假设，以及哪些关联页面需要路线更新。",
        ],
      },
    },
  },
};
